const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

console.log("Generating RSA 2048 Key Pair for SSO Account UI...");

const { privateKey } = crypto.generateKeyPairSync("rsa", {
  modulusLength: 2048,
});

const privateKeyPem = privateKey.export({ type: "pkcs8", format: "pem" });
const oneLinePem = privateKeyPem.replace(/\n/g, '\\n');

const envLocalPath = path.join(process.cwd(), '.env.local');

let envContent = '';
if (fs.existsSync(envLocalPath)) {
  envContent = fs.readFileSync(envLocalPath, 'utf8');
}

if (envContent.includes('RSA_PRIVATE_KEY_PEM=')) {
  console.log("RSA_PRIVATE_KEY_PEM already exists in .env.local. Replacing it...");
  envContent = envContent.replace(/RSA_PRIVATE_KEY_PEM=.*/g, `RSA_PRIVATE_KEY_PEM="${oneLinePem}"`);
} else {
  envContent += `\n# Generated by generate-rsa-key.js\nRSA_PRIVATE_KEY_PEM="${oneLinePem}"\n`;
}

fs.writeFileSync(envLocalPath, envContent.trim() + '\n');
console.log("✅ Successfully injected RSA_PRIVATE_KEY_PEM into .env.local!");
